import type { Metadata } from "next";
import { poppins, inter } from "../lib/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} ${inter.className}`}>
      <body>{children}</body>
    </html>
  );
}
